### ISSUE TITLE
Upgrade to D9/D10 or deprecate the module

### ISSUE THREAD

**Issue by andypost** [skilld-labs/skilld_backlink#2]
There's alternative, so it needs to point at README.md about deprecation and point to https://www.drupal.org/project/go_back

**Comment by davidferlay** [comment]
Let's deprecate if there is already community supported module

**Comment by andypost** [comment]
It needs one more step to deprecate module according to https://www.drupal.org/node/3215042 so users can get new release and consider move to dgo.to/go_back

**Comment by andypost** [comment]
https://getcomposer.org/doc/04-schema.md#abandoned you missed to add this
